version: "3.7"
services:
    web:
        image: nginx:latest
        working_dir: /var/www
        ports:
            - 8080:80
        volumes:
            - ./producer:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - producer
    producer:
        build:
            context: docker/.
            dockerfile: php.dockerfile
        working_dir: /var/www
        volumes:
            - ./producer:/var/www
    consumer:
        image: node:12-alpine
        working_dir: /var/www
        volumes: 
            - ./consumer:/var/www
        command: /bin/sh -c "sleep 20 && npm install && npm run dev"
    rabbitmq:
        image: rabbitmq:management-alpine
        ports:
            # The standard AMQP protocol port
            - '5672:5672'
            # HTTP management UI
            - '15672:15672'